Regex matching instead of traditional == matching :)
skittles9823/SkittBot pull request #42
Opened 2018-11-24 16:32 UTC by baalajimaestro

Tested filters, test blacklist(must work 99%) just incase, before merge :3

2018-12-21 03:13 UTC, skittles9823 requested changes
Do these the lemme know if you tested it.

2018-12-21 03:13 UTC, skittles9823 commented on tg_bot/modules/blacklist.py
> +    to_match=match_string.split(" ")
No spaces between =

2018-12-21 03:13 UTC, skittles9823 commented on tg_bot/modules/blacklist.py
> +            if re.fullmatch(keyword,word,flags=re.IGNORECASE):
Separate args with comma then space please.

2018-12-21 03:13 UTC, skittles9823 commented on tg_bot/modules/cust_filters.py
> +         if re.fullmatch(keyword,word, flags=re.IGNORECASE):
Separate args with comma then space please

2018-12-21 03:30 UTC, songotenks69 commented
Peru

2018-12-21 03:52 UTC, Yash-Garg commented
@songotenks69 K pro K

2018-12-21 05:27 UTC, baalajimaestro commented on tg_bot/modules/blacklist.py
> +            if re.fullmatch(keyword,word,flags=re.IGNORECASE):
Ok. Formatting ;-;

2018-12-21 05:27 UTC, baalajimaestro commented
I tested filters, will test blacklist also

2018-12-21 05:28 UTC, skittles9823 commented
@baalajimaestro Naisu

2018-12-21 05:28 UTC, SphericalKat commented
@skittles9823 What a wao

2018-12-21 05:28 UTC, baalajimaestro commented on tg_bot/modules/blacklist.py
> +    to_match=match_string.split(" ")
Oooof. You know I am bad at formatting ;-;

2018-12-21 05:29 UTC, baalajimaestro commented
Ok. Return back to shitpostclub @skittles9823 @ATechnoHazard 😂

2018-12-21 05:30 UTC, deletescape commented
@baalajimaestro Wew

2018-12-21 17:56 UTC, nitanmarcel commented
@deletescape .info

2018-12-22 10:16 UTC, baalajimaestro commented
Pushed, fixed formatted, tested to work :)
Can be merged. @skittles9823

2018-12-22 10:52 UTC, Yash-Garg commented
@baalajimaestro OwO

2018-12-22 14:12 UTC, yash-garg approved these changes

2018-12-22 14:35 UTC, rupansh commented
.casefold does the same. Does it not?

2018-12-24 01:37 UTC, skittles9823 commented
Whao

2018-12-24 01:37 UTC, merged